
var list = [
    {
        "name":"数字电视",
        "bg":"red",
        "width":1120,
        "height":560,
        "rowCount":6,
        "colCount":3,
        "spacing":5,
		"items":[
			{
				"name":"",
				"url":"#",
				"cls":"program",
                "rowCover":3,
                "colCover":2,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"1节目指南",
				"url":"#",
				"cls":"pro-post",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"2节目搜索",
				"url":"#",
				"cls":"pro-search",
                "rowCover":1,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":0
			},
			{
				"name":"3节目编辑",
				"url":"#",
				"cls":"pro-edit",
                "rowCover":1,
                "colCover":1,
                "coverFromX":5,
                "coverFromY":0
			},
			{
				"name":"4电子邮件",
				"url":"#",
				"cls":"e-mail",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			},
			{
				"name":"",
				"url":"#",
				"cls":"add-pic",
                "rowCover":2,
                "colCover":2,
                "coverFromX":4,
                "coverFromY":1
			},
			{
				"name":"6电视节目",
				"url":"#",
				"cls":"tv-pro",
                "rowCover":2,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":2
			},
			{
				"name":"7广播节目",
				"url":"#",
				"cls":"tv-bro",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":2
			},
			{
				"name":"8条件接收",
				"url":"#",
				"cls":"recive",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":2
			}
		]
    },
    {
        "name":"互动点播",
        "bg":"green",
        "width":1120,
        "height":560,
        "rowCount":6,
        "colCount":3,
        "spacing":5,
		"items":[
			{
				"name":"0",
				"url":"#",
				"cls":"kingdom",
                "rowCover":2,
                "colCover":3,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"1音乐+",
				"url":"#",
				"cls":"music",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"2爱奇艺",
				"url":"#",
				"cls":"aiqiyi",
                "rowCover":2,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":0
			},
			{
				"name":"3聚力",
				"url":"#",
				"cls":"pptv",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"4凤凰新闻网",
				"url":"#",
				"cls":"fh-news",
                "rowCover":1,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":1
			},
			{
				"name":"5有朋",
				"url":"#",
				"cls":"youpeng",
                "rowCover":1,
                "colCover":1,
                "coverFromX":5,
                "coverFromY":1
			},
			{
				"name":"6优酷",
				"url":"#",
				"cls":"youku",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":2
			},
			{
				"name":"7一方课堂",
				"url":"#",
				"cls":"yifang",
                "rowCover":2,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":2
			}
		]
    },
    {
        "name":"我的应用",
        "bg":"black",
        "width":1120,
        "height":560,
        "rowCount":4,
        "colCount":2,
        "spacing":5,
		"items":[
			{
				"name":"0我的应用",
				"url":"#",
				"cls":"myuse1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"1我的应用",
				"url":"#",
				"cls":"myuse2",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":0
			},
			{
				"name":"2我的应用",
				"url":"#",
				"cls":"myuse3",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"3我的应用",
				"url":"#",
				"cls":"myuse4",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"4我的应用",
				"url":"#",
				"cls":"myuse5",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":1
			},
			{
				"name":"5我的应用",
				"url":"#",
				"cls":"myuse6",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":1
			},
			{
				"name":"6我的应用",
				"url":"#",
				"cls":"myuse7",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"7我的应用",
				"url":"#",
				"cls":"myuse8",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			}
		]
    },
    {
        "name":"用户中心",
        "bg":"purple",
        "width":1120,
        "height":560,
        "rowCount":4,
        "colCount":2,
        "spacing":5,
		"items":[
			{
				"name":"0用户中心",
				"url":"#",
				"cls":"usermid1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"1用户中心",
				"url":"#",
				"cls":"usermid2",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":0
			},
			{
				"name":"2用户中心",
				"url":"#",
				"cls":"usermid3",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"3用户中心",
				"url":"#",
				"cls":"usermid4",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"4用户中心",
				"url":"#",
				"cls":"usermid5",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":1
			},
			{
				"name":"5用户中心",
				"url":"#",
				"cls":"usermid6",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":1
			},
			{
				"name":"6用户中心",
				"url":"#",
				"cls":"usermid7",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"7用户中心",
				"url":"#",
				"cls":"usermid8",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			}
		]
    },
    {
        "name":"系统设置",
        "bg":"black",
        "width":1120,
        "height":560,
        "rowCount":4,
        "colCount":2,
        "spacing":5,
		"items":[
			{
				"name":"0系统设置",
				"url":"#",
				"cls":"sysset1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"1系统设置",
				"url":"#",
				"cls":"sysset2",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":0
			},
			{
				"name":"2系统设置",
				"url":"#",
				"cls":"sysset3",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"3系统设置",
				"url":"#",
				"cls":"sysset4",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"4系统设置",
				"url":"#",
				"cls":"sysset5",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":1
			},
			{
				"name":"5系统设置",
				"url":"#",
				"cls":"sysset6",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":1
			},
			{
				"name":"6系统设置",
				"url":"#",
				"cls":"sysset7",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"7系统设置",
				"url":"#",
				"cls":"sysset8",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			}
		]
    }
]
