
var list = [
    {
        "name":"数字电视",
        "bg":"red",
        "width":1120,
        "height":560,
        "rowCount":6,
        "colCount":3,
        "spacing":5,
		"items":[
			{
				"name":"",
				"url":"#",
				"bg":"#222",
				"cls":"program",
                "rowCover":3,
                "colCover":2,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"节目指南",
				"url":"#",
				"bg":"green",
				"cls":"pro-post",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"节目搜索",
				"url":"#",
				"bg":"aquamarine",
				"cls":"pro-search",
                "rowCover":1,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":0
			},
			{
				"name":"节目编辑",
				"url":"#",
				"bg":"mediumpurple",
				"cls":"pro-edit",
                "rowCover":1,
                "colCover":1,
                "coverFromX":5,
                "coverFromY":0
			},
			{
				"name":"电子邮件",
				"url":"#",
				"bg":"cornflowerblue",
				"cls":"e-mail",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			},
			{
				"name":"",
				"url":"#",
				"bg":"url(img/timg.jpg)",
				"cls":"add-pic",
                "rowCover":2,
                "colCover":2,
                "coverFromX":4,
                "coverFromY":1
			},
			{
				"name":"",
				"url":"#",
				"bg":"url(img/vod_film.jpg)",
				"cls":"tv-pro",
                "rowCover":2,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":2
			},
			{
				"name":"广播节目",
				"url":"#",
				"bg":"purple",
				"cls":"tv-bro",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":2
			},
			{
				"name":"条件接收",
				"url":"#",
				"bg":"orange",
				"cls":"recive",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":2
			}
		]
    },
    {
        "name":"互动点播",
        "bg":"green",
        "width":1120,
        "height":560,
        "rowCount":6,
        "colCount":3,
        "spacing":5,
		"items":[
			{
				"name":"0",
				"url":"#",
				"bg":"url(img/gitta.jpg)",
				"cls":"kingdom",
                "rowCover":2,
                "colCover":3,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"音乐+",
				"url":"#",
				"bg":"cyan",
				"cls":"music",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"爱奇艺",
				"url":"#",
				"bg":"purple",
				"cls":"aiqiyi",
                "rowCover":2,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":0
			},
			{
				"name":"",
				"url":"#",
				"bg":"url(img/vod_film.jpg)",
				"cls":"pptv",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"凤凰新闻网",
				"url":"#",
				"bg":"blue",
				"cls":"fh-news",
                "rowCover":1,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":1
			},
			{
				"name":"优朋",
				"url":"#",
				"bg":"sienna",
				"cls":"youpeng",
                "rowCover":1,
                "colCover":1,
                "coverFromX":5,
                "coverFromY":1
			},
			{
				"name":"优酷",
				"url":"#",
				"bg":"mediumpurple",
				"cls":"youku",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":2
			},
			{
				"name":"义方课堂",
				"url":"#",
				"bg":"greenyellow",
				"cls":"yifang",
                "rowCover":2,
                "colCover":1,
                "coverFromX":4,
                "coverFromY":2
			}
		]
    },
    {
        "name":"我的应用",
        "bg":"black",
        "width":1120,
        "height":560,
        "rowCount":4,
        "colCount":2,
        "spacing":5,
		"items":[
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse2",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":0
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse3",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse4",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse5",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":1
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse6",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":1
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse7",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"我的应用",
				"url":"#",
				"bg":"cyan",
				"cls":"myuse8",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			}
		]
    },
    {
        "name":"用户中心",
        "bg":"purple",
        "width":1120,
        "height":560,
        "rowCount":4,
        "colCount":2,
        "spacing":5,
		"items":[
			{
				"name":"用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid2",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":0
			},
			{
				"name":"用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid3",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid4",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":0
			},
			{
				"name":"4用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid5",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":1
			},
			{
				"name":"用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid6",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":1
			},
			{
				"name":"用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid7",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			}/*,
			{
				"name":"7用户中心",
				"url":"#",
				"bg":"peru",
				"cls":"usermid8",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			}*/
		]
    },
    {
        "name":"系统设置",
        "bg":"black",
        "width":1120,
        "height":560,
        "rowCount":4,
        "colCount":2,
        "spacing":5,
		"items":[
			{
				"name":"系统设置",
				"url":"#",
				"bg":"orange",
				"cls":"sysset1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":0
			},
			{
				"name":"系统设置",
				"url":"#",
				"bg":"orange",
				"cls":"sysset1",
                "rowCover":1,
                "colCover":1,
                "coverFromX":1,
                "coverFromY":0
			},
			{
				"name":"系统设置",
				"url":"#",
				"bg":"orange",
				"cls":"sysset2",
                "rowCover":2,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":0
			},
			{
				"name":"系统设置",
				"url":"#",
				"bg":"orange",
				"cls":"sysset3",
                "rowCover":2,
                "colCover":1,
                "coverFromX":0,
                "coverFromY":1
			},
			{
				"name":"3系统设置",
				"url":"#",
				"bg":"orange",
				"cls":"sysset4",
                "rowCover":1,
                "colCover":1,
                "coverFromX":2,
                "coverFromY":1
			},
			{
				"name":"4系统设置",
				"url":"#",
				"bg":"orange",
				"cls":"sysset5",
                "rowCover":1,
                "colCover":1,
                "coverFromX":3,
                "coverFromY":1
			}
		]
    }
]



var items = ["数字电视","互动点播","我的应用","用户中心","系统设置"]
